---
- name: Install nsd
  apt:
    name: "{{ nsd_package }}"
    state: present

- name: Enable nsd
  service:
    name: "{{ nsd_service }}"
    enabled: yes

- name: Create zones directory
  file:
    path: "{{ __nsd_zones_dir }}"
    state: directory
    owner: root
    group: "{{ nsd_group }}"

- name: Create master directory
  file:
    path: "{{ __nsd_zones_dir }}/master"
    state: directory
    owner: root
    group: "{{ nsd_group }}"
    mode: 0755

- name: Create slave directory
  file:
    path: "{{ __nsd_zones_dir }}/slave"
    state: directory
    owner: root
    group: "{{ nsd_group }}"
    mode: 0775
